### PR TITLE
Add api

### PR DESCRIPTION
**Pull request by sazzamac**
#12 Create scanner page & #13 Connect API to app

### CODE REVIEW

**Review by Sajni94 — APPROVED** [review]
all works well for me!

**Comment by KejPat** [comment]
This is very cool! Works very smoothly. Just a couple of things from a UI perspective. Can the camera reach the full screen, there a margins on the left and right, at least there is on my phone so can those be removed. And with the text like "Requesting for camera permission" I'm assuming that will be another task to add styling?

**Comment by KejPat** [comment]
Also can you just add brief comments above functions so that we can see what it does quickly if we ever look back

**Comment by sazzamac** [comment]
> This is very cool! Works very smoothly. Just a couple of things from a UI perspective. Can the camera reach the full screen, there a margins on the left and right, at least there is on my phone so can those be removed. And with the text like "Requesting for camera permission" I'm assuming that will be another task to add styling?

Do you mean margins top and bottom? I can't seem to resolve these styles to fit full screen. Feel like I'm spending a bit too much time on it so I will create an issue that can be picked up later, if that's ok.

**Review by KejPat — APPROVED** [review]

**Pull request merged**
