### PR TITLE
added bottom navigation bar

### PR DESCRIPTION
**Pull request by KejPat**
Created a navigation bar with image icons and added remaining screens

### CODE REVIEW

**Comment by sazzamac** [comment]
Looks great Kej!

**Comment by sazzamac** [comment]
image

**Comment by KejPat** [comment]
@sazzamac do you mean the header? I haven't added that in, I made that a separate issue but can add it here if you would like?

**Comment by sazzamac** [comment]
So the title 'Hey' is written over the time - maybe a container is needed for this?

**Comment by KejPat** [comment]
Yeah it's because I've taken the header that was in there before out so all the text is shifted up. I'll try and add that back in now

**Review by Sajni94 — APPROVED** [review]
works fine for me!

**Comment by sazzamac** [comment]
great, fixed on android for me now :)

**Review by sazzamac — APPROVED** [review]

**Pull request merged**
