### PR TITLE
homepage-layout

### PR DESCRIPTION
**Pull request by Sajni94**
Updates to the homepage layout

### CODE REVIEW

**Comment by KejPat** [comment]
Nice one Saj, having the logic for the earth in there is good. For the drop down the width of the items list is wider than the picker itself, can it be lined up? Also the drop down currently overlaps the picker. Can that be moved down slightly so it doesn't cover it?

**Comment by Sajni94** [comment]
Ah okay yeh I see what you mean, will update tomorrow. I also couldn't get the default value to work and then forgot about it, so I need to fix that tomorrow too

**Comment by Sajni94** [comment]
nevermind, have updated was a quick fix coming back with a fresh pair of eyes!

**Review by sazzamac — APPROVED** [review]
This is a great start to the homepage Saj. The next step will be to link data and make the dropdowns reactive.

**Review by KejPat — APPROVED** [review]

**Review by sazzamac — APPROVED** [review]
Looks good!

**Pull request merged**
