### PR TITLE
Upload initial animation

### PR DESCRIPTION
**Pull request by sazzamac**

### CODE REVIEW

**Comment by KejPat** [comment]
image

When you first go on the page the island starts lower than it should be on that page

**Comment by KejPat** [comment]
Also when you tap of the page and visit the other screens and then go back on it, it gets stuck as the above image I sent

**Comment by sazzamac** [comment]
> image
> 
> When you first go on the page the island starts lower than it should be on that page

Oh no, this doesn't happen for me :/ I'll have to find another way of making it full screen

**Comment by sazzamac** [comment]
> Also when you tap off the page and visit the other screens and then go back on it, it gets stuck as the above image I sent

Yeah the image should be adjusted so it's in the right position or what do you expect to see in this case?

**Review by Sajni94 — APPROVED** [review]
looks amazing Sara!!

**Review by KejPat — APPROVED** [review]

**Pull request merged**
