### PR TITLE
Get JSON data and add to item screen

### PR DESCRIPTION
**Pull request by KejPat**
Changes to styling
Add percentage impact progress circle
Updated item information

### CODE REVIEW

**Comment by sazzamac** [comment]
merge conflicts

**Comment by sazzamac** [comment]
Getting an error

Can't find variable: MyTheme in App.py

**Comment by sazzamac** [comment]
Merge conflicts

**Comment by sazzamac** [comment]
Got warning: Virtalized lists should never be nested inside plain scrollviews with the same orientation

**Comment by sazzamac** [comment]
Warning: componentsWillReceiveProps has been renamed

**Comment by sazzamac** [comment]
If the eco score is unknown I wouldn't necessarily say 0% impact... although not sure what could be put in place instead

**Comment by sazzamac** [comment]
This looks really great

**Comment by KejPat** [comment]
Yeah I saw those warnings and ignored them lol because I spent too long on it, so can put them in the issues as a bug

**Review by sazzamac — APPROVED** [review]

**Review by Sajni94 — APPROVED** [review]

**Pull request merged**
